version: '3.4'

services:
  unityregisterapp:
    image: unityregisterapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
